<?php

/**
 * Implements hook_menu().
 */
function custom_counter_menu() {
  $items = array();
  $items['counter-page'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('used_by_form'),
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Счетчик просмотров ноды
 */
/**
 * Implements hook_node_view_alter().
 */
function custom_counter_node_view_alter(&$build) {
  if ($build['#node']->type == 'services') {
    $node = node_load($build['#node']->nid);
//  Увеличиваем значение поля "field_count_views", если загрудается страница с нодой
    if (isset($node->field_count_views['und'][0]['value'])) {
      $node->field_count_views['und'][0]['value']++;
      node_save($node);
    }
  }
}

/**
 * Счетчик посещений. Форма "я посетил"
 */
// Кнопка для добавления пользователя в список "я посетил"
function used_by_form($form, &$form_state) {
  global $user;
  $nid = explode('/', $_GET['q']);
  if (isset($nid[1])) {
    $form['username'] = array(
      '#type' => 'hidden',
      '#states' => 'invisible',
      '#value' => $user->uid,
    );
    $form['service'] = array(
      '#type' => 'hidden',
      '#states' => 'invisible',
      '#value' => $nid[1],
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Я воспользовался этой услугой'),
      '#submit' => array('_used_by_form_submit'),
    );
  }
  return $form;
}

/**
 * Implements hook_form_validate
 */
function used_by_form_validate($form, &$form_state) {
  $uid = $form_state['values']['username'];
  $used_by_user = user_load($uid);
  $nid = $form_state['values']['service'];
  $node = node_load($nid);
  if (isset($node->field_used_by['und'])) {
    foreach ($node->field_used_by['und'] as $uid) {
      if ($used_by_user->uid == $uid['uid']) {
        form_set_error('username', 'Вы уже подтверждали, что воспользовались услугой');
        drupal_goto('/node/' . $node->nid);
      }
    }
  }
}

/**
 * Callback submit
 * Implements hook_form_submit
 */
function _used_by_form_submit($form, &$form_state) {

  $uid = $form_state['values']['username'];
  $used_by_user = user_load($uid);
  $nid = $form_state['values']['service'];
  $node = node_load($nid);

  $node->field_used_by['und'][]['uid'] = $used_by_user->uid;

  drupal_set_message('Вы подтвердили, что воспользовались данной услугой');
  node_save($node);
}

// Редирект на форму логин, если незарегистрированный пользователь хочет добавить новый проект
/**
 * Implements hook_init().
 */
function custom_counter_init() {
  global $user;
  $url = request_uri();
  if ($url == '/node/add/services' && in_array('anonymous user', $user->roles)) {
    drupal_set_message(t('Вам необходимо войти на сайт или зарегистрироваться, чтобы добавить новый проект'), 'warning', FALSE);
    drupal_goto('user/login');
  }
}
